[package]
name = "pulsitoapp_api"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

actix-web = "3"

[env]
FOO = "bar"
MYSQLCLIENT_LIB_DIR = { value = "connector\mysqlclient.lib", relative = true }
